export const ADD_ELEMENT = "ADD_ELEMENT";
export const READ_ALL_GENRE = "READ_ALL_GENRE";
export const ADD_ALL_ELEMENTS = "ADD_ALL_ELEMENTS";
export const READ_ALL_ELEMENTS = "READ_ALL_ELEMENTS";
export const READ_ALL_CATEGORY = "READ_ALL_CATEGORY";
export const READ_BY_UUID = "READ_BY_UUID";
